apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-nginx
  name: my-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: my-nginx
  type: {{ .Values.service.type }}  
status:
  loadBalancer: {}
