apiVersion: v1
kind: ConfigMap
metadata:
  ##name: mychart-configmap
  # Built-In object .Release.Name 
  name: {{ .Release.Name }}
data:
  myvalue: "Sample Config Map"
  #Read from values.yaml
  costCode: {{ .Values.costCode }}
  #Template Function
  Zone: {{ quote .Values.infra.zone }}
  Region: {{ quote .Values.infra.region }}
  projectCode: {{ upper .Values.projectCode }}
  #Template Function and Pipeline and Default Values
  ##pipeline: {{ .Values.projectCode | upper | quote }}
  ##now: {{ now | date "2006-01-02" | quote}}
  ##contact: {{ .Values.contact | default "12345678890" | quote }}
  #Flow Control - if/else
  {{- if eq .Values.infra.region "us-e" }}
  ha: {{ .Values.infra.region }}
  {{- else if eq .Values.infra.region "us-w" }}
  ha: {{ .Values.infra.region }}
  {{- else }}
  ha: {{ .Values.infra.region }}
  {{- end }}
  #Restricted Scope, we cannot access the built-in objects directly
  {{- with .Values.tags }}
  Machine Type: {{ .machine | default "NA" | quote }}
  Rack ID: {{ .rack | quote }}
  Storage Type: {{ .drive | upper | quote }}
  Video Card: {{ .vcard | quote }}
  {{- end }}
  #Looping
  Lang Used: |-
    {{- range .Values.LangUsed }}
    - {{. | title | quote }}
    {{- end}}
